[package]
name = "rustysearch"
authors = ["Alex Wellnitz <moin@wellnitz-alex.de>"]
version = "0.1.0"
edition = "2021"
readme = "README.md"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
